apps/travelbuddy/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    # Login & Registration #
    url(r'^$', views.index),
    url(r'^register/$', views.register),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),

    # Main Site Pages
    url(r'^travels/$', views.main),
    url(r'^travels/add/$', views.add),
    url(r'^travels/trip/(?P<id>\d+)/$', views.show),
    url(r'^travels/users/$', views.UsersView.as_view()),

    # User Actions #
    url(r'^travels/add/post/$', views.post),
    url(r'^travels/trip/(?P<id>\d+)/join/$', views.join),

]

blackbelt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.travelbuddy.urls')),
    url(r'^admin/', admin.site.urls),
]

settings/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.travelbuddy.urls')),
    url(r'^admin/', admin.site.urls),
]

# Routing for Django Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/travelbuddy/models.py
from __future__ import unicode_literals
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
import bcrypt
from datetime import datetime


# Form Validations

def nameMinLength(value):
    if len(value) < 3:
        raise ValidationError('"{}" is too short. Use at least 3 characters.'.format(value))

def pwMinLength(value):
    if len(value) < 8:
        raise ValidationError('Password must be at least 8 characters.')


### User & Trip models ###

class User(models.Model):
    name = models.CharField(max_length=45, validators=[nameMinLength])
    username = models.CharField(max_length=45, validators=[nameMinLength])
    password = models.CharField(max_length=100, validators=[pwMinLength])
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # When called in shell, return in string format
    def __str__(self):
        return '{} ({})'.format(self.name, self.username)

    # Returns url to access an instance of the model.
    def get_absolute_url(self):
        return reverse('view', args=[str(self.id)])

class Trip(models.Model):
    destination = models.CharField(max_length=45)
    start = models.DateTimeField()
    end = models.DateTimeField()
    plans = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Trip.objects.get(id=1).host gets the User hosting Trip1
    # User.objects.get(id=1).hosting.all() gets the trips User1 will host
    host = models.ForeignKey(User, related_name="hosting")

    # Trip.objects.get(id=1).users.all() gets the users going on Trip1
    # User.objects.get(id=1).going.all() gets the trips User1 is going on
    users = models.ManyToManyField(User, related_name="going")

    # When called in shell, return in string format
    def __str__(self):
        return '{}: {} - {} ({})'.format(
            self.destination,
            self.start.strftime('%m/%d'),
            self.end.strftime('%m/%d'),
            self.end.strftime('%Y'),
            )

apps/travelbuddy/forms.py
from django import forms
from django.core.exceptions import ValidationError
from models import User, Trip


# Need to fix validations

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = '__all__'

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get("password")
        confirm = cleaned_data.get("confirmation")

        if password != confirm:
            raise ValidationError("Your password entries do not match!")


# Need to fix validations

class LoginForm(forms.Form):
    username = forms.CharField(max_length=45)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)



# Need to validate for time

class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['destination','start','end','plans']
        exclude = ['added', 'updated','host','users']

apps/travelbuddy/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views import generic
from models import User, Trip
from forms import RegisterForm, LoginForm, TripForm
import bcrypt




# TO Implement:
# - Django's class-based forms (with validation)
# - Django's session approach (login required)
# - Django's user model
# - Django's authentication model
# - OAuth 2.0


### Login & Registration ###

# /
def index(request):
    # (auth) Include forms from forms.py
    forms = {
        "registration": RegisterForm(),
        "login": LoginForm()
        }
    return render(request, 'travelbuddy/index.html', forms)


# /register/
def register(request):
    if request.method == 'GET': # Block GET requests
        return redirect('/')

    # (auth) Test post data against RegisterForm validations
    post_data = RegisterForm(request.POST)
    if not post_data.is_valid():

        # NEED TO FIX FLASH INVALIDATIONS HERE

        # messages.error(request, "You must log back in to join another trip.")
        # Flash error messages to page
        # for field, message in post_data.errors: # will this work?
        #     messages.error(request, message, extra_tags=field)
        return redirect('/')

    else: # Create User -- stick with this or use Django's approach?
        User.objects.create(
            name = request.POST["name"],
            username = request.POST["username"],

            # Encrypt user password and store in DB
            password = bcrypt.hashpw(
                request.POST["password"].encode(), bcrypt.gensalt()
            )
        )

        # (auth) Create new user
        # default params: username, email, and password
        # for password, Django implements its own encryption
        # user = User.objects.create_user(
        #     request.POST["username"],
        #     email = None,
        #     password = request.POST["password"] )

        # # additional param: 'name'
        # user.name = request.POST["name"]

        # Store session for login and queries
        request.session['user'] = request.POST["username"]
        return redirect('/travels/')


# /login/
def login(request):
    if request.method == 'GET':
        return redirect('/')

    # (auth) Test post data against RegisterForm validations
    post_data = LoginForm(request.POST)
    if not post_data.is_valid():

        # NEED TO FIX FLASH INVALIDATIONS HERE
        
        # Flash error messages to page
        # for field, message in post_data.errors: # will this work?
        #     messages.error(request, message, extra_tags=field)
        return redirect('/')

    else: # If inputs valid, store session for login and queries
        request.session['user'] = request.POST["username"]
        return redirect('/travels/')


# /logout/
def logout(request):
    if 'user' in request.session:
        request.session.flush() # Deletes session data and cookie
        messages.error(request, "You have ended your session. Thank you!")
    return redirect('/')




### Main Site ###

# /travels/
def main(request):
    if not 'user' in request.session: # Redirect logged out user
        messages.error(request, "You must login to view our site.")
        return redirect('/')

    # Use username in session to query user info
    user = User.objects.get(username=request.session['user'])
    
    data = {
        # get user info
        "user": user,

        # get trip lists:
        "user_trips": user.going.all(), # where user is going
        "other_trips": Trip.objects.exclude(users=user) # not going
    }
    return render(request, 'travelbuddy/main.html', data)

# /travels/add/
def add(request):
    if not 'user' in request.session:
        messages.error(request, "You must login to view our site.")
        return redirect('/')
    form = { "addtrip" : TripForm() }
    return render(request, 'travelbuddy/add.html', form)

# /travels/trip/<id>/
def show(request, id):
    if not 'user' in request.session:
        messages.error(request, "You must login to view our site.")
        return redirect('/')

    data = {
        # get individual trip info
        "trip": Trip.objects.get(id=id),

        # get all users going (via template: IF user = host, exclude!)
        "users": Trip.objects.get(id=id).users.all()
    }
    return render(request, 'travelbuddy/show.html', data)

# /travels/users/
class UsersView(generic.ListView):
    model = User
    queryset = User.objects.all().order_by('name')
    template_name = 'travelbuddy/users.html'



### User Actions ###

# /travels/trip/<id>/join/
def join(request, id):
    if not 'user' in request.session: # Redirect logged out user
        messages.error(request, "You must log back in to join another trip.")
        return redirect('/')

    # Add user in session to trip
    Trip.objects.get(id=id).users.add(
        User.objects.get(username=request.session['user']))
    return redirect('/travels/')

# /travels/add/post/
def post(request):
    if request.method == 'GET':
        return redirect('/travels/add/')
    
    # validate and show errors
    errors = Trip.objects.validate(request.POST)
    if len(errors):
        for field, message in errors.iteritems():
            messages.error(request, message, extra_tags=field)
        return redirect('/travels/add/')

    else: # create new trip
        Trip.objects.create(
            destination = request.POST["destination"],
            plan = request.POST["plan"],
            start = request.POST["start"],
            end = request.POST["end"],
            host = User.objects.get(username=request.session['user'])
        )

        # Add user in session to trip as one of the 'users'
        # On the trip page, don't show on list via IF statement
        Trip.objects.last().users.add(
            User.objects.get(username=request.session['user']))
        return redirect('/travels/')

apps/travelbuddy/templates/travelbuddy/add.html
<!DOCTYPE html>
<head>
<meta charset=UTF-8>
<title>Travel Buddy</title>
{% load static %}
<link rel="stylesheet" href="{% static 'travelbuddy/style.css' %}">
</head>
<body>
<container>

<div>
    <h3>Add a Trip</h3>
    <p>
        <a href="/travels/">Home</a><br>
        <a href="/travels/users/">Users</a><br>
        <a href=/logout/>Logout</a>
    </p>

    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}

</div>

<div>
    <fieldset>
    <form action=/travels/add/post/ method=post>
        {% csrf_token %}
        {{ addtrip.as_p }}
        <p><input type="submit" value="Add"></p>
    </form>
    </fieldset>
</div>

</container>
</body>
</html>

apps/travelbuddy/templates/travelbuddy/index.html
<!DOCTYPE html>
<head>
<meta charset=UTF-8>
<title>Travel Buddy</title>
{% load static %}
<link rel="stylesheet" href="{% static 'travelbuddy/style.css' %}">
</head>
<body>

<h1>Welcome to Travel Buddy!</h1>

<container>

<div>
    <fieldset>
    <legend>Login</legend>
    <form action=/login/ method=post>
        {% csrf_token %}
        <!-- "as_p" = paragraphs; also "as_table" and "as_ul" -->
        {{ login.as_p }}
        <p><input type=submit value=Login></p>
    </form>
    </fieldset>
</div>

<div>
    <fieldset>
    <legend>Registration</legend>
    <form action=/register/ method=post>
        {% csrf_token %}
        {{ registration.as_p }}
        <p><input type="submit" value="Register"></p>
    </form>
    </fieldset>
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>

{{post_data.name}}

</container>
</body>
</html>

apps/travelbuddy/templates/travelbuddy/main.html
<!DOCTYPE html>
<head>
<meta charset=UTF-8>
<title>Travel Buddy</title>
{% load static %}
<link rel="stylesheet" href="{% static 'travelbuddy/style.css' %}">
</head>
<body>
<container>

<div>
    <h3>Hello, {{user.username}}!</h3>
    <p><a href="add/">Add Travel Plan</a><br>
    <a href="/travels/users/">Users</a><br>
    <a href=/logout/>Logout</a></p>

    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}

</div>

<div>
    <h3>Your Trips</h3>
    <table>
    <tr>
        <td>Destination</td>
        <td>Start</td>
        <td>End</td>
        <td>Plan</td>
    </tr>
    {% for trip in user_trips %}
    <tr>
        <td><a href=trip/{{trip.id}}/>{{trip.destination}}</a></td>
        <td>{{trip.start|date:"F j, Y"}}</td>
        <td>{{trip.end|date:"F j, Y"}}</td>
        <td>{{trip.plans}}</td>
    </tr>
    {% endfor %}
    </table>

    <h3>Other User's Travel Plans</h3>
    <table>
    <tr>
        <td>Host</td>
        <td>Destination</td>
        <td>Start</td>
        <td>End</td>
        <td>Wanna Join?</td>
    </tr>
    {% for trip in other_trips %}
    <tr>
        <td>{{trip.host.name}}</td>
        <td><a href=trip/{{trip.id}}/>{{trip.destination}}</a></td>
        <td>{{trip.start|date:"F j, Y"}}</td>
        <td>{{trip.end|date:"F j, Y"}}</td>
        <td><a href="trip/{{trip.id}}/join">Join</a></td>
    </tr>
    {% endfor %}
    </table>
</div>

</container>
</body>
</html>

apps/travelbuddy/templates/travelbuddy/show.html
<!DOCTYPE html>
<head>
<meta charset=UTF-8>
<title>Travel Buddy</title>
{% load static %}
<link rel="stylesheet" href="{% static 'travelbuddy/style.css' %}">
</head>
<body>
<container>

<div>
    <h3>Trip Info</h3>
    <p>
        <a href="/travels/">Home</a><br>
        <a href="/travels/users/">Users</a><br>
        <a href=/logout/>Logout</a>
    </p>

    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}

</div>

<div>
    <h3>{{trip.destination}}</h3>
    <p>Host: {{trip.host.name}}</p>
    <p>Plans: {{trip.plans}}</p>
    <p>Travel Date From: {{trip.start|date:"F j, Y"}}</p>
    <p>Travel Date To: {{trip.end|date:"F j, Y"}}</p>
    <hr>

    <h3>Who Else is Going?</h3>
    {% for user in users %}
        {% if user != trip.host %}
        <p>{{user.name}}</p>
        {% endif %}
    {% endfor %}
</div>

</container>
</body>
</html>

apps/travelbuddy/templates/travelbuddy/users.html
<!DOCTYPE html>
<head>
<meta charset=UTF-8>
<title>Travel Buddy</title>
{% load static %}
<link rel="stylesheet" href="{% static 'travelbuddy/style.css' %}">
</head>
<body>
<container>

<div>
    <h3>User List</h3>
    <p><a href="/travels/">Home</a><br>
    <a href="add/">Add Travel Plan</a><br>
    <a href=/logout/>Logout</a></p>

    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}

</div>

<div>
    <h3>Site Users</h3>
    <table>
    <tr>
        <td>Name</td>
        <td>Username</td>
        <td>Member Since</td>
    </tr>
    {% for user in user_list %}
    <tr>
        <td>{{user.name}}</td>
        <td>{{user.username}}</td>
        <td>{{user.added}}</td>
    </tr>
    {% endfor %}
    </table>

</div>

</container>
</body>
</html>